import Head from 'next/head'
import Image from 'next/image'
import Menu from '../components/Layout/Menu/Menu'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout/Layout'
import Timer from '@/components/Timer/Timer'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>Pomodoro App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Timer/>
      </Layout>
    </>
  )
}
